spring.application.name=RondasTecnologia

# Local Database Configuration
appUrl=jdbc:postgresql://localhost:5432/RondasTecnologia
spring.datasource.url=${appUrl}
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA Configuration (assuming Hibernate)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


